"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-xc7*@10zyz@+bas%1v7i&-uoyu_3q)29d6_+jk$@os2-e6e-+_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS 設定
allowed_hosts_str = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_str.split(',') if h.strip()]
# 生產環境自動加入 .onrender.com
if not DEBUG:
    ALLOWED_HOSTS.append('.onrender.com')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'store',
]

WSGI_APPLICATION = 'config.wsgi.application'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 必須在 CommonMiddleware 之前
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 靜態檔案服務（生產環境）
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Use PostgreSQL if DATABASE_URL is set, otherwise fallback to SQLite
DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()

if DATABASE_URL:
    try:
        db_config = dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
        # Django 5.1+ supports psycopg3, ensure we use it
        if 'ENGINE' in db_config and 'postgresql' in db_config['ENGINE']:
            # Force use of psycopg3 adapter
            db_config['OPTIONS'] = db_config.get('OPTIONS', {})
        DATABASES = {
            'default': db_config
        }
    except (ValueError, Exception) as e:
        # If DATABASE_URL is invalid, fallback to SQLite
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- API / CORS settings ---
# CORS 設定：允許的前端來源
FRONTEND_URL = os.environ.get('FRONTEND_URL', '').strip()
CORS_ALLOWED_ORIGINS = [
    # 本地開發
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    # Render 生產環境
    "https://market-frontend-seh3.onrender.com",
]
# 如果 FRONTEND_URL 有值且格式正確，加入列表
if FRONTEND_URL and (FRONTEND_URL.startswith('http://') or FRONTEND_URL.startswith('https://')):
    if FRONTEND_URL not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)
# 移除重複值和空值
CORS_ALLOWED_ORIGINS = [origin for origin in set(CORS_ALLOWED_ORIGINS) if origin and origin.strip()]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
}

# Session 安全設定（資安強化）
SESSION_COOKIE_HTTPONLY = True  # 防止 JavaScript 存取 Session Cookie
SESSION_COOKIE_SECURE = not DEBUG  # 生產環境（HTTPS）設為 True，開發環境（HTTP）設為 False
SESSION_COOKIE_SAMESITE = "None" if not DEBUG else "Lax"  # 跨站需要 None，開發環境用 Lax
SESSION_COOKIE_AGE = 86400  # Session 過期時間：24 小時（秒）
SESSION_SAVE_EVERY_REQUEST = True  # 每次請求都更新 Session 過期時間
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 關閉瀏覽器不立即過期（使用 SESSION_COOKIE_AGE）

# CSRF 保護設定
CSRF_COOKIE_HTTPONLY = False  # 前端需要讀取 CSRF Token
CSRF_COOKIE_SECURE = not DEBUG  # 生產環境（HTTPS）設為 True，開發環境（HTTP）設為 False
CSRF_COOKIE_SAMESITE = "None" if not DEBUG else "Lax"  # 跨站需要 None，開發環境用 Lax
# 只包含有效的 URL（必須有 scheme）
CSRF_TRUSTED_ORIGINS = [
    origin for origin in CORS_ALLOWED_ORIGINS
    if origin and (origin.startswith('http://') or origin.startswith('https://'))
]

# CORS 設定（允許認證）
CORS_ALLOW_CREDENTIALS = True  # 允許傳送 Cookie（Session）

# 安全性：僅允許白名單的 origin（CORS_ALLOWED_ORIGINS）
# 不要開啟 CORS_ALLOW_ALL_ORIGINS = True，否則任何網站都能存取 API
