# Generated by Django 5.1.4 on 2026-01-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', max_length=20, unique=True)),
                ('line_oa_id', models.CharField(default='@032emqnn', max_length=50)),
                ('bank_name_code', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
