# Generated by Django 5.1.4 on 2026-01-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_has_variants_productspec_productspecoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
