# Generated by Django 5.1.4 on 2026-01-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productvariant_image_url'),
    ]

    operations = [
        # 先移除 ProductVariant 的 spec_options 欄位
        migrations.RemoveField(
            model_name='productvariant',
            name='spec_options',
        ),
        # 先刪除模型
        migrations.DeleteModel(
            name='ProductSpecOption',
        ),
        migrations.DeleteModel(
            name='ProductSpec',
        ),
        # 先加入新欄位
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        # 然後修改 ProductVariant 的選項和約束
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'name')},
        ),
    ]
